appDir = "/home/pi/HiJo"
usbDir = "/media" # Raspbian: "/media/pi"
environmentConfigFile = "hijo_environment.ini"
deviceConfigFile = "hijo_device.ini"
configSection = "HiJo"
versionFilename = "app/version.txt"